name: 'jprm-build'
description: 'Builds a Jellyfin plugin via Jellyfin Plugin Repository Manager'
author: 'Odd Stråbø'

branding:
  icon: package
  color: purple

inputs:
  path:
    required: false
    default: '.'
    description: 'The path to the sources of the plugin solution (default: ".")'
  output:
    required: false
    default: './artifacts'
    description: 'Path to dotnet build directory (default: ./artifacts)'
  version:
    required: false
    default: ''
    description: 'Overwrite the detected version of the plugin (default: "")'
  changelog:
    required: false
    default: ''
    description: 'Overwrite the detected changelog of the plugin, supports multiline values (default: "")'
  dotnet-config:
    required: false
    default: 'Release'
    description: 'The dotnet build configuration (default: Release)'
  dotnet-target:
    required: false
    default: ''
    description: 'Overwrite the detected dotnet target framework used for the plugin build (default: "")'
  max-cpu-count:
    required: false
    default: '1'
    description: 'Maximum number of processors to use during build (default: "1")'
  verbosity:
    required: false
    default: 'debug'
    description: 'The log verbosity of JPRM'

outputs:
  artifact:
    description: 'Returns the built plugin zip'
    value: ${{ steps.build.outputs.artifact }}

runs:
  using: composite
  steps:
    - name: Ensure ouput dir exists
      shell: bash
      run: |-
        echo "::group::Preparing Environment"
        mkdir -p ${{ inputs.output }}

    - name: Setup JRPM Deps
      shell: bash
      env:
        # PEP 668 can burn.
        PIP_BREAK_SYSTEM_PACKAGES: '1'
      run: |-
        python3 -m pip config set global.break-system-packages true

        python3 -m pip install -r ${{ github.action_path }}/requirements.txt
        echo "::endgroup::"

    - id: build
      name: Run JPRM build
      shell: bash
      env:
        GH_ACTION_PATH: ${{ github.action_path }}
        INPUTS_CHANGELOG: ${{ inputs.changelog }}
        INPUTS_DOTNET_CONFIG: ${{ inputs.dotnet-config }}
        INPUTS_DOTNET_TARGET: ${{ inputs.dotnet-target }}
        INPUTS_MAX_CPU_COUNT: ${{ inputs.max-cpu-count }}
        INPUTS_OUTPUT: ${{ inputs.output }}
        INPUTS_PATH: ${{ inputs.path }}
        INPUTS_VERBOSITY: ${{ inputs.verbosity }}
        INPUTS_VERSION: ${{ inputs.version }}
      run: |-
        echo "::group::Building and Packaging"

        if [[ -n "${INPUTS_DOTNET_TARGET}" ]]; then
          DOTNET_FRAMEWORK="--dotnet-framework ${INPUTS_DOTNET_TARGET}"
        else
          DOTNET_FRAMEWORK=""
        fi

        if [[ -n "${INPUTS_VERSION}" ]]; then
          PLUGIN_VERSION="-v ${INPUTS_VERSION}"
        else
          PLUGIN_VERSION=""
        fi

        if [[ -n "${INPUTS_CHANGELOG}" ]]; then
          PLUGIN_CHANGELOG="--changelog \"${INPUTS_CHANGELOG}\""
        else
          PLUGIN_CHANGELOG=""
        fi

        artifact="$(python3 ${GH_ACTION_PATH}/jprm/__init__.py --verbosity=${INPUTS_VERBOSITY} plugin build ${INPUTS_PATH} -o ${INPUTS_OUTPUT} ${PLUGIN_VERSION} ${PLUGIN_CHANGELOG} --dotnet-configuration ${INPUTS_DOTNET_CONFIG} --max-cpu-count ${INPUTS_MAX_CPU_COUNT} ${DOTNET_FRAMEWORK})"

        echo "Artifact: ${artifact}"
        echo "artifact=${artifact}" >> $GITHUB_OUTPUT
        echo "::endgroup::"
