from pathlib import Path

import pytest
from click.testing import CliRunner
from testfixtures import compare, LogCapture
import jprm

from .test_utils import TEST_DATA_DIR, json_load


@pytest.mark.datafiles(
    TEST_DATA_DIR / "pluginA_1.0.0.zip",
    TEST_DATA_DIR / "manifest_pluginA.json",
)
@pytest.mark.parametrize(
    "url",
    [
        "http://example.org/plugins/pluginA_1.0.0.zip",
        "https://example.org/pluginA.zip",
        "https://ipfs.io/ipfs/Qme7ss3ARVgxv6rXqVPiikMJ8u2NLgmgszg13pYrDKEoiu",
        "ipfs://Qme7ss3ARVgxv6rXqVPiikMJ8u2NLgmgszg13pYrDKEoiu",
        "ipfs://bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq/wiki/Vincent_van_Gogh.html",
    ],
)
def test_repo_add(
    url: str,
    cli_runner: CliRunner,
    tmp_path: Path,
    datafiles: Path,
):
    manifest_file = tmp_path / "repo.json"
    result = cli_runner.invoke(
        jprm.cli, ["--verbosity=debug", "repo", "init", str(manifest_file)]
    )
    assert result.exit_code == 0

    manifest_a = json_load(datafiles / "manifest_pluginA.json")
    manifest_a[0]["versions"][0]["sourceUrl"] = url

    with LogCapture("jprm") as capture:
        cli_runner.invoke(
            jprm.cli,
            [
                "--verbosity=debug",
                "repo",
                "add",
                str(manifest_file),
                str(datafiles / "pluginA_1.0.0.zip"),
                "--plugin-url",
                url,
            ],
        )
        manifest = json_load(manifest_file)
        compare(manifest, manifest_a)

        capture.check_present(
            (
                "jprm",
                "INFO",
                f"Plugin url `{url}` overrides the autogenerated `/plugin-a/plugin-a_1.0.0.0.zip`.",
            ),
        )

    assert not (tmp_path / "plugin-a" / "plugin-a_1.0.0.0.zip").exists()
