name: Publish Python Package

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      upload_url:
        required: true
        description: upload url of the release the assets need to get uploaded to

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install twine

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          retention-days: 30
          if-no-files-found: error
          path: dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*

      - name: Upload GitHub Release Artifacts
        uses: shogo82148/actions-upload-release-asset@v1
        if: ${{ github.event_name == 'release' }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: 'dist/*'
          overwrite: true

      - name: Upload GitHub Release Artifacts (Manual trigger)
        uses: shogo82148/actions-upload-release-asset@v1
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: 'dist/*'
          overwrite: true
